---
title: "Texas Power Crisis (February 2021)"
author: "Sofia Sark"
format: html
editor: visual
---

## Initial Set Up

```{r}
#| output: false
# Loading necessary libraries
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(stars)
```

### Loading in and Cleaning Data

Night Lights
```{r}
#| output: false
# Loading in raster (night light) data
feb7_tile5 <- read_stars(here("data/VNP46A1/VNP46A1.A2021038.h08v05.001.2021039064328.tif"))
feb7_tile6 <- read_stars(here("data/VNP46A1/VNP46A1.A2021038.h08v06.001.2021039064329.tif"))
feb16_tile5 <- read_stars(here("data/VNP46A1/VNP46A1.A2021047.h08v05.001.2021048091106.tif"))
feb16_tile6 <- read_stars(here("data/VNP46A1/VNP46A1.A2021047.h08v06.001.2021048091105.tif"))
```

```{r}
# Merging rasters together, by day
feb7_lights <- st_mosaic(feb7_tile5, feb7_tile6)
feb16_lights <- st_mosaic(feb16_tile5, feb16_tile6)
```

```{r}
# Finding difference in light instensity
diff_light <-  feb7_lights - feb16_lights
```

```{r}
diff_mask <- diff_light
diff_mask[diff_mask < 200] <- NA
```

```{r}
vector_diff_mask <- diff_mask %>% 
  st_as_sf() %>% 
  st_make_valid()
```

```{r}
crop_box <- st_bbox(c(xmin = -96.5, xmax = -94.5, ymin = 29, ymax = 30.5), crs = st_crs(diff_mask)) %>% 
  st_as_sfc()
```

```{r}
diff_cropped <- st_intersects()
```

