---
title: "scratch"
format: html
---
latitudes of tiles 5 and 6
```{r}
tm_shape(feb7_tile5) +
  tm_raster() +
  tm_grid() +
tm_shape()

tm_shape(feb7_tile6) +
  tm_raster() +
  tm_grid()
```

```{r}
# trying to find the opposite of census blackout DELETE
census_noblackout_sgbp <- st_disjoint(census_blackout, census_tracts)
census_noblackout_logical <- lengths(census_noblackout_sgbp) < 0
census_noblackout <- census_tracts[census_noblackout_logical,]

# Joining tract data to match census data that experienced blackouts DELETE?
houses_tracts <- st_join(income_tracts, census_blackout, join = st_within)

if(ncell(census_tracts) == ncell(census_blackout)){
  warning("Filtering did not remove cells")
} else {
  print("Filtering successfully removed cells")
}
```

```{r}
both_plots <- tmap_arrange(feb7_plot, feb16_plot, legend_map) 
legend_map

legend_map <-  tm_shape(feb7_cropped) +
  tm_raster(breaks = c(0, 100, 200, 300, 400, 500, Inf),
            palette = night_light_colors,
            title = "Light Intensity (nW cm-2sr-1)") +
  tm_title(text = "February 7, 2021") +
  tm_graticules(alpha = 0.5) +
  tm_layout(legend.only = TRUE) 
```

